# DF Firmas✍️

## Extract
Extreamos los datos de firmas espectroradiometricos para que sea más facil procesarlos

In [2]:
import polars as pl
import numpy as np

In [3]:
# Leer el archivo de texto con Polars
file_path = '../processing/PSR-1100f_SN22A44H3_00037.txt'

In [ ]:
# Función para procesar líneas del archivo y extraer solo Reflect (Y)
def extraer_reflect(line):
    try:
        return float(line.strip().split('\t')[1])  # Extrae Reflect. % (segunda columna)
    except (ValueError, IndexError):
        return None  # Ignorar líneas no válidas

# Leer el archivo y procesar solo la columna Reflect (Y)
with open(file_path, 'r') as file:
    reflect_data = [extraer_reflect(line) for line in file if "\t" in line]

# Filtrar valores válidos (eliminar None)
reflect_data = [reflect for reflect in reflect_data if reflect is not None]

# Aplanar los datos
y_list = np.array(reflect_data, dtype=float)

# Mostrar la lista de Reflect. % (Y)
y_list
# mean = np.mean(y_list, axis=0, dtype=float)
# mean

In [18]:
# Función para procesar líneas del archivo y extraer solo Reflect (Y)
def extraer_wvl(line):
    try:
        return float(line.strip().split('\t')[0])  # Extrae Reflect. % (segunda columna)
    except (ValueError, IndexError):
        return None  # Ignorar líneas no válidas

# Leer el archivo y procesar solo la columna Reflect (Y)
with open(file_path, 'r') as file:
    wvl_data = [extraer_wvl(line) for line in file if "\t" in line]

# Filtrar valores válidos (eliminar None)
wvl_data = [wvl for wvl in wvl_data if wvl is not None]

# Aplanar los datos
x_list = np.array(wvl_data, dtype=float)

# Mostrar la lista de Reflect. % (Y)
x_list

array([ 320.,  321.,  322.,  323.,  324.,  325.,  326.,  327.,  328.,
        329.,  330.,  331.,  332.,  333.,  334.,  335.,  336.,  337.,
        338.,  339.,  340.,  341.,  342.,  343.,  344.,  345.,  346.,
        347.,  348.,  349.,  350.,  351.,  352.,  353.,  354.,  355.,
        356.,  357.,  358.,  359.,  360.,  361.,  362.,  363.,  364.,
        365.,  366.,  367.,  368.,  369.,  370.,  371.,  372.,  373.,
        374.,  375.,  376.,  377.,  378.,  379.,  380.,  381.,  382.,
        383.,  384.,  385.,  386.,  387.,  388.,  389.,  390.,  391.,
        392.,  393.,  394.,  395.,  396.,  397.,  398.,  399.,  400.,
        401.,  402.,  403.,  404.,  405.,  406.,  407.,  408.,  409.,
        410.,  411.,  412.,  413.,  414.,  415.,  416.,  417.,  418.,
        419.,  420.,  421.,  422.,  423.,  424.,  425.,  426.,  427.,
        428.,  429.,  430.,  431.,  432.,  433.,  434.,  435.,  436.,
        437.,  438.,  439.,  440.,  441.,  442.,  443.,  444.,  445.,
        446.,  447.,  448.,  449.,  450.,  451.,  452.,  453.,  454.,
        455.,  456.,  457.,  458.,  459.,  460.,  461.,  462.,  463.,
        464.,  465.,  466.,  467.,  468.,  469.,  470.,  471.,  472.,
        473.,  474.,  475.,  476.,  477.,  478.,  479.,  480.,  481.,
        482.,  483.,  484.,  485.,  486.,  487.,  488.,  489.,  490.,
        491.,  492.,  493.,  494.,  495.,  496.,  497.,  498.,  499.,
        500.,  501.,  502.,  503.,  504.,  505.,  506.,  507.,  508.,
        509.,  510.,  511.,  512.,  513.,  514.,  515.,  516.,  517.,
        518.,  519.,  520.,  521.,  522.,  523.,  524.,  525.,  526.,
        527.,  528.,  529.,  530.,  531.,  532.,  533.,  534.,  535.,
        536.,  537.,  538.,  539.,  540.,  541.,  542.,  543.,  544.,
        545.,  546.,  547.,  548.,  549.,  550.,  551.,  552.,  553.,
        554.,  555.,  556.,  557.,  558.,  559.,  560.,  561.,  562.,
        563.,  564.,  565.,  566.,  567.,  568.,  569.,  570.,  571.,
        572.,  573.,  574.,  575.,  576.,  577.,  578.,  579.,  580.,
        581.,  582.,  583.,  584.,  585.,  586.,  587.,  588.,  589.,
        590.,  591.,  592.,  593.,  594.,  595.,  596.,  597.,  598.,
        599.,  600.,  601.,  602.,  603.,  604.,  605.,  606.,  607.,
        608.,  609.,  610.,  611.,  612.,  613.,  614.,  615.,  616.,
        617.,  618.,  619.,  620.,  621.,  622.,  623.,  624.,  625.,
        626.,  627.,  628.,  629.,  630.,  631.,  632.,  633.,  634.,
        635.,  636.,  637.,  638.,  639.,  640.,  641.,  642.,  643.,
        644.,  645.,  646.,  647.,  648.,  649.,  650.,  651.,  652.,
        653.,  654.,  655.,  656.,  657.,  658.,  659.,  660.,  661.,
        662.,  663.,  664.,  665.,  666.,  667.,  668.,  669.,  670.,
        671.,  672.,  673.,  674.,  675.,  676.,  677.,  678.,  679.,
        680.,  681.,  682.,  683.,  684.,  685.,  686.,  687.,  688.,
        689.,  690.,  691.,  692.,  693.,  694.,  695.,  696.,  697.,
        698.,  699.,  700.,  701.,  702.,  703.,  704.,  705.,  706.,
        707.,  708.,  709.,  710.,  711.,  712.,  713.,  714.,  715.,
        716.,  717.,  718.,  719.,  720.,  721.,  722.,  723.,  724.,
        725.,  726.,  727.,  728.,  729.,  730.,  731.,  732.,  733.,
        734.,  735.,  736.,  737.,  738.,  739.,  740.,  741.,  742.,
        743.,  744.,  745.,  746.,  747.,  748.,  749.,  750.,  751.,
        752.,  753.,  754.,  755.,  756.,  757.,  758.,  759.,  760.,
        761.,  762.,  763.,  764.,  765.,  766.,  767.,  768.,  769.,
        770.,  771.,  772.,  773.,  774.,  775.,  776.,  777.,  778.,
        779.,  780.,  781.,  782.,  783.,  784.,  785.,  786.,  787.,
        788.,  789.,  790.,  791.,  792.,  793.,  794.,  795.,  796.,
        797.,  798.,  799.,  800.,  801.,  802.,  803.,  804.,  805.,
        806.,  807.,  808.,  809.,  810.,  811.,  812.,  813.,  814.,
        815.,  816.,  817.,  818.,  819.,  820.,  821.,  822.,  823.,
        824.,  825.,  826.,  827.,  828.,  829.,  830.,  831.,  832.,
        833.,  834.,  835.,  836.,  837.,  838.,  839.,  840.,  841.,
        842.,  843.,  844.,  845.,  846.,  847.,  848.,  849.,  850.,
        851.,  852.,  853.,  854.,  855.,  856.,  857.,  858.,  859.,
        860.,  861.,  862.,  863.,  864.,  865.,  866.,  867.,  868.,
        869.,  870.,  871.,  872.,  873.,  874.,  875.,  876.,  877.,
        878.,  879.,  880.,  881.,  882.,  883.,  884.,  885.,  886.,
        887.,  888.,  889.,  890.,  891.,  892.,  893.,  894.,  895.,
        896.,  897.,  898.,  899.,  900.,  901.,  902.,  903.,  904.,
        905.,  906.,  907.,  908.,  909.,  910.,  911.,  912.,  913.,
        914.,  915.,  916.,  917.,  918.,  919.,  920.,  921.,  922.,
        923.,  924.,  925.,  926.,  927.,  928.,  929.,  930.,  931.,
        932.,  933.,  934.,  935.,  936.,  937.,  938.,  939.,  940.,
        941.,  942.,  943.,  944.,  945.,  946.,  947.,  948.,  949.,
        950.,  951.,  952.,  953.,  954.,  955.,  956.,  957.,  958.,
        959.,  960.,  961.,  962.,  963.,  964.,  965.,  966.,  967.,
        968.,  969.,  970.,  971.,  972.,  973.,  974.,  975.,  976.,
        977.,  978.,  979.,  980.,  981.,  982.,  983.,  984.,  985.,
        986.,  987.,  988.,  989.,  990.,  991.,  992.,  993.,  994.,
        995.,  996.,  997.,  998.,  999., 1000., 1001., 1002., 1003.,
       1004., 1005., 1006., 1007., 1008., 1009., 1010., 1011., 1012.,
       1013., 1014., 1015., 1016., 1017., 1018., 1019., 1020., 1021.,
       1022., 1023., 1024., 1025., 1026., 1027., 1028., 1029., 1030.,
       1031., 1032., 1033., 1034., 1035., 1036., 1037., 1038., 1039.,
       1040., 1041., 1042., 1043., 1044., 1045., 1046., 1047., 1048.,
       1049., 1050., 1051., 1052., 1053., 1054., 1055., 1056., 1057.,
       1058., 1059., 1060., 1061., 1062., 1063., 1064., 1065., 1066.,
       1067., 1068., 1069., 1070., 1071., 1072., 1073., 1074., 1075.,
       1076., 1077., 1078., 1079., 1080., 1081., 1082., 1083., 1084.,
       1085., 1086., 1087., 1088., 1089., 1090., 1091., 1092., 1093.,
       1094., 1095., 1096., 1097., 1098., 1099., 1100.])

**En caso de extraerme ambos**

In [43]:
# Función para procesar líneas del archivo
def procesar_linea(line):
    try:
        wvl, reflect = map(float, line.strip().split('\t'))
        return wvl, reflect
    except ValueError:
        return None, None

# Leer y procesar el archivo en una sola línea
with open(file_path, 'r') as file:
    datos = [procesar_linea(line) for line in file if "\t" in line]

# Filtrar los valores válidos (no None)
wvl_data, reflect_data = zip(*[(wvl, reflect) for wvl, reflect in datos if wvl is not None and reflect is not None])

# Crear un DataFrame de Polars
df = pl.DataFrame({
    "X": wvl_data,
    "Y": reflect_data
})

# Convertir las columnas a listas (si se desea)
x_list = df['X'].to_list()
y_list = df['Y'].to_list()

# Mostrar las listas de X (Wvl) y Y (Reflect)
print("Lista de Wvl (X):", x_list)
print("Lista de Reflect. % (Y):", y_list)

# median = np.array(y_list, axis=1, dtype=float).mean()
# print(f"Median \n {median}")

Lista de Wvl (X): [320.0, 321.0, 322.0, 323.0, 324.0, 325.0, 326.0, 327.0, 328.0, 329.0, 330.0, 331.0, 332.0, 333.0, 334.0, 335.0, 336.0, 337.0, 338.0, 339.0, 340.0, 341.0, 342.0, 343.0, 344.0, 345.0, 346.0, 347.0, 348.0, 349.0, 350.0, 351.0, 352.0, 353.0, 354.0, 355.0, 356.0, 357.0, 358.0, 359.0, 360.0, 361.0, 362.0, 363.0, 364.0, 365.0, 366.0, 367.0, 368.0, 369.0, 370.0, 371.0, 372.0, 373.0, 374.0, 375.0, 376.0, 377.0, 378.0, 379.0, 380.0, 381.0, 382.0, 383.0, 384.0, 385.0, 386.0, 387.0, 388.0, 389.0, 390.0, 391.0, 392.0, 393.0, 394.0, 395.0, 396.0, 397.0, 398.0, 399.0, 400.0, 401.0, 402.0, 403.0, 404.0, 405.0, 406.0, 407.0, 408.0, 409.0, 410.0, 411.0, 412.0, 413.0, 414.0, 415.0, 416.0, 417.0, 418.0, 419.0, 420.0, 421.0, 422.0, 423.0, 424.0, 425.0, 426.0, 427.0, 428.0, 429.0, 430.0, 431.0, 432.0, 433.0, 434.0, 435.0, 436.0, 437.0, 438.0, 439.0, 440.0, 441.0, 442.0, 443.0, 444.0, 445.0, 446.0, 447.0, 448.0, 449.0, 450.0, 451.0, 452.0, 453.0, 454.0, 455.0, 456.0, 457.0, 458.0, 459.0, 460.0, 461.0, 462.0, 463.0, 464.0, 465.0, 466.0, 467.0, 468.0, 469.0, 470.0, 471.0, 472.0, 473.0, 474.0, 475.0, 476.0, 477.0, 478.0, 479.0, 480.0, 481.0, 482.0, 483.0, 484.0, 485.0, 486.0, 487.0, 488.0, 489.0, 490.0, 491.0, 492.0, 493.0, 494.0, 495.0, 496.0, 497.0, 498.0, 499.0, 500.0, 501.0, 502.0, 503.0, 504.0, 505.0, 506.0, 507.0, 508.0, 509.0, 510.0, 511.0, 512.0, 513.0, 514.0, 515.0, 516.0, 517.0, 518.0, 519.0, 520.0, 521.0, 522.0, 523.0, 524.0, 525.0, 526.0, 527.0, 528.0, 529.0, 530.0, 531.0, 532.0, 533.0, 534.0, 535.0, 536.0, 537.0, 538.0, 539.0, 540.0, 541.0, 542.0, 543.0, 544.0, 545.0, 546.0, 547.0, 548.0, 549.0, 550.0, 551.0, 552.0, 553.0, 554.0, 555.0, 556.0, 557.0, 558.0, 559.0, 560.0, 561.0, 562.0, 563.0, 564.0, 565.0, 566.0, 567.0, 568.0, 569.0, 570.0, 571.0, 572.0, 573.0, 574.0, 575.0, 576.0, 577.0, 578.0, 579.0, 580.0, 581.0, 582.0, 583.0, 584.0, 585.0, 586.0, 587.0, 588.0, 589.0, 590.0, 591.0, 592.0, 593.0, 594.0, 595.0, 596.0, 597.0, 598.0, 599.0, 600.0, 601.0, 602.0, 603.0, 604.0, 605.0, 606.0, 607.0, 608.0, 609.0, 610.0, 611.0, 612.0, 613.0, 614.0, 615.0, 616.0, 617.0, 618.0, 619.0, 620.0, 621.0, 622.0, 623.0, 624.0, 625.0, 626.0, 627.0, 628.0, 629.0, 630.0, 631.0, 632.0, 633.0, 634.0, 635.0, 636.0, 637.0, 638.0, 639.0, 640.0, 641.0, 642.0, 643.0, 644.0, 645.0, 646.0, 647.0, 648.0, 649.0, 650.0, 651.0, 652.0, 653.0, 654.0, 655.0, 656.0, 657.0, 658.0, 659.0, 660.0, 661.0, 662.0, 663.0, 664.0, 665.0, 666.0, 667.0, 668.0, 669.0, 670.0, 671.0, 672.0, 673.0, 674.0, 675.0, 676.0, 677.0, 678.0, 679.0, 680.0, 681.0, 682.0, 683.0, 684.0, 685.0, 686.0, 687.0, 688.0, 689.0, 690.0, 691.0, 692.0, 693.0, 694.0, 695.0, 696.0, 697.0, 698.0, 699.0, 700.0, 701.0, 702.0, 703.0, 704.0, 705.0, 706.0, 707.0, 708.0, 709.0, 710.0, 711.0, 712.0, 713.0, 714.0, 715.0, 716.0, 717.0, 718.0, 719.0, 720.0, 721.0, 722.0, 723.0, 724.0, 725.0, 726.0, 727.0, 728.0, 729.0, 730.0, 731.0, 732.0, 733.0, 734.0, 735.0, 736.0, 737.0, 738.0, 739.0, 740.0, 741.0, 742.0, 743.0, 744.0, 745.0, 746.0, 747.0, 748.0, 749.0, 750.0, 751.0, 752.0, 753.0, 754.0, 755.0, 756.0, 757.0, 758.0, 759.0, 760.0, 761.0, 762.0, 763.0, 764.0, 765.0, 766.0, 767.0, 768.0, 769.0, 770.0, 771.0, 772.0, 773.0, 774.0, 775.0, 776.0, 777.0, 778.0, 779.0, 780.0, 781.0, 782.0, 783.0, 784.0, 785.0, 786.0, 787.0, 788.0, 789.0, 790.0, 791.0, 792.0, 793.0, 794.0, 795.0, 796.0, 797.0, 798.0, 799.0, 800.0, 801.0, 802.0, 803.0, 804.0, 805.0, 806.0, 807.0, 808.0, 809.0, 810.0, 811.0, 812.0, 813.0, 814.0, 815.0, 816.0, 817.0, 818.0, 819.0, 820.0, 821.0, 822.0, 823.0, 824.0, 825.0, 826.0, 827.0, 828.0, 829.0, 830.0, 831.0, 832.0, 833.0, 834.0, 835.0, 836.0, 837.0, 838.0, 839.0, 840.0, 841.0, 842.0, 843.0, 844.0, 845.0, 846.0, 847.0, 848.0, 849.0, 850.0, 851.0, 852.0, 853.0, 854.0, 855.0, 856.0, 857.0, 858.0, 859.0, 860.0, 861.0, 862.0, 863.0, 864.0, 865.0, 866.0, 867.0, 868.0, 869.0, 870.0, 871.0, 872.0, 873.0, 874.0, 875.0, 876.0, 877.0, 878.0, 879.0, 880.0, 881.0, 882.0, 883.0, 884.0, 885.0, 886.0, 887.0, 888.0, 889.0, 890.0, 891.0, 892.0, 893.0, 894.0, 895.0, 896.0, 897.0, 898.0, 899.0, 900.0, 901.0, 902.0, 903.0, 904.0, 905.0, 906.0, 907.0, 908.0, 909.0, 910.0, 911.0, 912.0, 913.0, 914.0, 915.0, 916.0, 917.0, 918.0, 919.0, 920.0, 921.0, 922.0, 923.0, 924.0, 925.0, 926.0, 927.0, 928.0, 929.0, 930.0, 931.0, 932.0, 933.0, 934.0, 935.0, 936.0, 937.0, 938.0, 939.0, 940.0, 941.0, 942.0, 943.0, 944.0, 945.0, 946.0, 947.0, 948.0, 949.0, 950.0, 951.0, 952.0, 953.0, 954.0, 955.0, 956.0, 957.0, 958.0, 959.0, 960.0, 961.0, 962.0, 963.0, 964.0, 965.0, 966.0, 967.0, 968.0, 969.0, 970.0, 971.0, 972.0, 973.0, 974.0, 975.0, 976.0, 977.0, 978.0, 979.0, 980.0, 981.0, 982.0, 983.0, 984.0, 985.0, 986.0, 987.0, 988.0, 989.0, 990.0, 991.0, 992.0, 993.0, 994.0, 995.0, 996.0, 997.0, 998.0, 999.0, 1000.0, 1001.0, 1002.0, 1003.0, 1004.0, 1005.0, 1006.0, 1007.0, 1008.0, 1009.0, 1010.0, 1011.0, 1012.0, 1013.0, 1014.0, 1015.0, 1016.0, 1017.0, 1018.0, 1019.0, 1020.0, 1021.0, 1022.0, 1023.0, 1024.0, 1025.0, 1026.0, 1027.0, 1028.0, 1029.0, 1030.0, 1031.0, 1032.0, 1033.0, 1034.0, 1035.0, 1036.0, 1037.0, 1038.0, 1039.0, 1040.0, 1041.0, 1042.0, 1043.0, 1044.0, 1045.0, 1046.0, 1047.0, 1048.0, 1049.0, 1050.0, 1051.0, 1052.0, 1053.0, 1054.0, 1055.0, 1056.0, 1057.0, 1058.0, 1059.0, 1060.0, 1061.0, 1062.0, 1063.0, 1064.0, 1065.0, 1066.0, 1067.0, 1068.0, 1069.0, 1070.0, 1071.0, 1072.0, 1073.0, 1074.0, 1075.0, 1076.0, 1077.0, 1078.0, 1079.0, 1080.0, 1081.0, 1082.0, 1083.0, 1084.0, 1085.0, 1086.0, 1087.0, 1088.0, 1089.0, 1090.0, 1091.0, 1092.0, 1093.0, 1094.0, 1095.0, 1096.0, 1097.0, 1098.0, 1099.0, 1100.0]
Lista de Reflect. % (Y): [5.5093, 5.1217, 5.6154, 6.541, 6.6815, 6.1388, 5.5745, 6.4759, 8.0085, 9.7189, 10.875, 11.0712, 10.5653, 9.9249, 9.9023, 9.8876, 8.9924, 9.0899, 9.1209, 7.621, 5.9055, 4.6448, 4.7489, 4.6706, 4.3415, 3.6752, 2.5007, 1.8929, 2.6697, 3.5416, 4.1583, 4.19, 3.7009, 3.0361, 2.4665, 1.8848, 1.2392, 0.5473, 0.1259, 0.1737, 0.7221, 1.1151, 1.3181, 1.2927, 1.1586, 1.0141, 0.9035, 0.6961, 0.7031, 0.968, 1.2501, 1.8479, 2.6447, 2.8963, 3.0108, 3.0157, 2.6653, 2.3002, 2.0114, 1.836, 1.6503, 1.4992, 1.7489, 1.7941, 1.6429, 1.977, 2.1006, 2.0211, 1.9535, 2.0755, 2.2179, 1.9274, 1.6243, 1.4314, 1.5614, 1.5602, 1.4869, 1.5846, 1.781, 1.8809, 1.4132, 1.0543, 0.8375, 0.6662, 0.6035, 0.6985, 1.0885, 1.3651, 1.4827, 1.4248, 1.4042, 1.3928, 1.2444, 1.2624, 1.3983, 1.4803, 1.5195, 1.4946, 1.3368, 1.3032, 1.3613, 1.3909, 1.298, 1.1488, 1.1107, 1.177, 1.2907, 1.3487, 1.1474, 0.8948, 1.1593, 1.1836, 1.0798, 1.324, 1.2376, 0.9902, 1.1451, 1.1764, 1.124, 1.1977, 1.2753, 1.3048, 1.1783, 1.0983, 1.103, 1.2604, 1.2215, 1.0791, 1.2442, 1.2773, 1.1732, 1.361, 1.3437, 1.1177, 1.132, 1.2052, 1.2742, 1.2036, 1.1288, 1.0997, 1.2294, 1.2381, 1.0623, 1.0404, 1.1173, 1.2604, 1.2581, 1.2182, 1.1831, 1.1718, 1.198, 1.2615, 1.2676, 1.239, 1.1885, 1.0976, 1.0808, 1.2218, 1.1798, 1.1609, 1.312, 1.3049, 1.2355, 1.2273, 1.2591, 1.2832, 1.2324, 1.215, 1.2395, 1.3132, 1.3856, 1.436, 1.4312, 1.395, 1.3546, 1.3808, 1.455, 1.545, 1.5113, 1.5644, 1.7018, 1.6238, 1.5901, 1.6946, 1.8104, 1.9492, 2.1107, 2.2112, 2.2626, 2.2727, 2.3794, 2.5303, 2.6909, 2.7736, 2.8397, 2.9675, 3.1515, 3.3725, 3.5994, 3.6874, 3.7088, 3.9387, 4.1025, 4.1773, 4.3195, 4.4649, 4.6009, 4.7584, 4.8771, 4.9391, 5.0545, 5.1682, 5.2438, 5.3191, 5.4022, 5.5079, 5.5665, 5.6007, 5.6526, 5.6609, 5.6538, 5.7085, 5.7801, 5.8455, 5.8202, 5.8305, 5.9095, 5.9682, 6.0177, 6.0578, 6.0555, 6.0501, 6.0706, 6.0924, 6.1129, 6.1293, 6.1358, 6.1268, 6.0857, 6.0674, 6.0707, 6.0472, 6.0119, 5.9671, 5.9168, 5.861, 5.7998, 5.734, 5.6616, 5.5794, 5.4961, 5.4138, 5.3379, 5.2458, 5.1496, 5.0905, 5.0596, 5.0427, 4.9651, 4.8852, 4.8254, 4.7739, 4.7265, 4.679, 4.6186, 4.5573, 4.5101, 4.4771, 4.452, 4.4131, 4.3854, 4.3682, 4.3235, 4.2964, 4.3004, 4.259, 4.2216, 4.2231, 4.175, 4.1168, 4.1189, 4.1106, 4.092, 4.0874, 4.0619, 4.0113, 4.0133, 4.0112, 3.976, 3.9535, 3.9298, 3.8935, 3.8517, 3.8059, 3.7567, 3.7257, 3.7041, 3.6035, 3.5324, 3.5303, 3.5289, 3.5266, 3.5164, 3.4951, 3.4655, 3.4262, 3.4152, 3.4323, 3.4446, 3.451, 3.4488, 3.4296, 3.4072, 3.3963, 3.3808, 3.3536, 3.2999, 3.2408, 3.178, 3.1026, 3.0341, 2.9771, 2.9042, 2.8117, 2.6901, 2.5728, 2.4732, 2.4172, 2.3742, 2.3363, 2.2857, 2.2376, 2.199, 2.1832, 2.185, 2.2041, 2.2047, 2.1834, 2.1284, 2.099, 2.098, 2.0596, 2.0155, 1.9802, 1.9303, 1.8907, 1.9156, 1.8933, 1.8374, 1.8214, 1.7915, 1.7387, 1.7585, 1.797, 1.8074, 1.8119, 1.813, 1.8108, 1.8315, 1.8744, 1.9083, 1.9385, 1.9648, 2.0145, 2.0861, 2.1785, 2.2888, 2.4167, 2.559, 2.7443, 2.9823, 3.2525, 3.5601, 3.9133, 4.2635, 4.6202, 5.0234, 5.4439, 5.8737, 6.3252, 6.7681, 7.1716, 7.5504, 7.9136, 8.2902, 8.6457, 8.9756, 9.2922, 9.5905, 9.8683, 10.1315, 10.3813, 10.619, 10.85, 11.0779, 11.3233, 11.5409, 11.7024, 11.8914, 12.0854, 12.2454, 12.4123, 12.5898, 12.7651, 12.9289, 13.0741, 13.2106, 13.3307, 13.4147, 13.5146, 13.6338, 13.7416, 13.8386, 13.9225, 13.9963, 14.0638, 14.1318, 14.1975, 14.2603, 14.3174, 14.3702, 14.419, 14.4709, 14.5164, 14.5362, 14.5608, 14.5926, 14.6151, 14.6384, 14.6675, 14.6835, 14.6917, 14.7012, 14.7033, 14.7002, 14.7204, 14.745, 14.759, 14.7403, 14.7095, 14.7382, 14.7682, 14.7827, 14.7718, 14.7562, 14.7565, 14.7581, 14.7597, 14.7571, 14.7629, 14.7802, 14.7943, 14.7992, 14.7795, 14.7688, 14.771, 14.7766, 14.7783, 14.7699, 14.783, 14.7994, 14.7835, 14.7905, 14.8212, 14.8108, 14.7906, 14.7861, 14.7929, 14.8049, 14.8, 14.8039, 14.8227, 14.8241, 14.8201, 14.8201, 14.8177, 14.8122, 14.8002, 14.7995, 14.8213, 14.8379, 14.8473, 14.8418, 14.8411, 14.849, 14.8412, 14.8363, 14.8541, 14.8615, 14.8598, 14.8554, 14.8597, 14.88, 14.8732, 14.8587, 14.8715, 14.8732, 14.8616, 14.8634, 14.8637, 14.8456, 14.8632, 14.8989, 14.8872, 14.8727, 14.871, 14.8752, 14.884, 14.8951, 14.9087, 14.9234, 14.9339, 14.9278, 14.8853, 14.8846, 14.9154, 14.9297, 14.9184, 14.8689, 14.8783, 14.9074, 14.8896, 14.8728, 14.8665, 14.8747, 14.8828, 14.8729, 14.884, 14.911, 14.8871, 14.8727, 14.9012, 14.9141, 14.9122, 14.8985, 14.8974, 14.9163, 14.9142, 14.9023, 14.8951, 14.8996, 14.9152, 14.9326, 14.9371, 14.9087, 14.8938, 14.8897, 14.8749, 14.867, 14.8754, 14.8785, 14.8716, 14.8363, 14.8144, 14.8191, 14.8671, 14.9138, 14.8701, 14.8502, 14.8772, 14.8789, 14.8642, 14.8317, 14.8244, 14.8422, 14.8442, 14.8445, 14.8502, 14.8513, 14.847, 14.8321, 14.823, 14.8295, 14.8422, 14.8607, 14.8909, 14.8959, 14.8658, 14.8734, 14.8861, 14.8448, 14.8239, 14.8372, 14.8093, 14.7753, 14.7741, 14.7824, 14.7962, 14.8128, 14.8133, 14.7726, 14.7462, 14.7417, 14.7677, 14.7902, 14.7801, 14.7701, 14.759, 14.7332, 14.7062, 14.6847, 14.6782, 14.6802, 14.6578, 14.6475, 14.6707, 14.6644, 14.6433, 14.664, 14.6759, 14.6586, 14.6206, 14.5773, 14.5647, 14.5576, 14.5489, 14.5231, 14.4888, 14.4613, 14.4457, 14.4443, 14.4541, 14.4682, 14.4716, 14.4707, 14.4662, 14.4179, 14.3591, 14.3537, 14.3291, 14.2706, 14.2287, 14.2087, 14.2371, 14.2232, 14.1461, 14.0927, 14.0571, 14.0395, 14.0126, 13.9703, 13.9776, 13.9977, 13.9602, 13.9558, 14.0033, 14.0368, 14.0433, 13.9804, 13.9623, 14.0143, 13.9793, 13.9107, 13.9163, 13.9231, 13.9134, 13.919, 13.9396, 13.9922, 13.998, 13.9349, 13.9301, 13.96, 14.0045, 13.9968, 13.8951, 13.8752, 13.897, 13.8711, 13.9007, 14.0414, 14.0253, 13.9068, 13.9302, 13.9855, 14.0284, 14.0604, 14.0743, 14.0317, 13.9869, 13.9817, 13.9765, 13.975, 14.0585, 14.1354, 14.1155, 14.0591, 13.9863, 14.0326, 14.1237, 14.1935, 14.213, 14.1711, 14.1359, 14.1105, 14.1159, 14.1214, 14.1186, 14.1605, 14.1881, 14.0298, 13.9426, 14.0448, 14.14, 14.218, 14.2512, 14.2572, 14.2488, 14.179, 14.0659, 14.1359, 14.2265, 14.116, 14.1073, 14.2622, 14.2503, 14.1804, 14.2735, 14.3816, 14.4607, 14.4071, 14.2692, 14.2642, 14.26, 14.1628, 14.1423, 14.1934, 14.0866, 13.9905, 14.1269, 14.2559, 14.3261, 14.3415, 14.3122, 14.2267, 14.2317, 14.4182, 14.4044, 14.2525, 14.2735, 14.2358, 13.9413, 13.8361, 13.9684, 14.4353, 14.8507, 14.4127, 14.0409, 14.113, 14.3471, 14.6841, 14.927, 15.0718, 15.1031, 14.8314, 14.3134, 14.2584, 14.3669, 14.2596, 14.2085, 14.3073, 14.4755, 14.6991, 14.9879, 15.1105, 14.8203, 14.6206, 14.6005, 14.5365, 14.3672, 13.7926, 13.5136, 13.8953, 13.9656, 13.7841, 14.8229, 15.7109, 14.4502, 13.8112, 14.4028, 14.2681]

**DF combinado**

In [5]:
# Función para procesar líneas del archivo y extraer valores
def extraer_valores(line):
    try:
        # Extrae Wvl (primera columna) y Reflect (segunda columna)
        wvl = float(line.strip().split('\t')[0])  # Extrae Wvl
        reflect = float(line.strip().split('\t')[1])  # Extrae Reflect
        return wvl, reflect
    except (ValueError, IndexError):
        return None, None  # Ignorar líneas no válidas

# Inicializar listas para Wvl y Reflect
x = []
y = []

# Leer el archivo y procesar las líneas
with open(file_path, 'r') as file:
    for line in file:
        if "\t" in line:
            wvl, reflect = extraer_valores(line)
            if wvl is not None:  # Filtrar valores válidos
                x.append(wvl)
            if reflect is not None:  # Filtrar valores válidos
                y.append(reflect)

# Aplanar los datos
x_list = x
y_list = y


print(y_list)

[5.5093, 5.1217, 5.6154, 6.541, 6.6815, 6.1388, 5.5745, 6.4759, 8.0085, 9.7189, 10.875, 11.0712, 10.5653, 9.9249, 9.9023, 9.8876, 8.9924, 9.0899, 9.1209, 7.621, 5.9055, 4.6448, 4.7489, 4.6706, 4.3415, 3.6752, 2.5007, 1.8929, 2.6697, 3.5416, 4.1583, 4.19, 3.7009, 3.0361, 2.4665, 1.8848, 1.2392, 0.5473, 0.1259, 0.1737, 0.7221, 1.1151, 1.3181, 1.2927, 1.1586, 1.0141, 0.9035, 0.6961, 0.7031, 0.968, 1.2501, 1.8479, 2.6447, 2.8963, 3.0108, 3.0157, 2.6653, 2.3002, 2.0114, 1.836, 1.6503, 1.4992, 1.7489, 1.7941, 1.6429, 1.977, 2.1006, 2.0211, 1.9535, 2.0755, 2.2179, 1.9274, 1.6243, 1.4314, 1.5614, 1.5602, 1.4869, 1.5846, 1.781, 1.8809, 1.4132, 1.0543, 0.8375, 0.6662, 0.6035, 0.6985, 1.0885, 1.3651, 1.4827, 1.4248, 1.4042, 1.3928, 1.2444, 1.2624, 1.3983, 1.4803, 1.5195, 1.4946, 1.3368, 1.3032, 1.3613, 1.3909, 1.298, 1.1488, 1.1107, 1.177, 1.2907, 1.3487, 1.1474, 0.8948, 1.1593, 1.1836, 1.0798, 1.324, 1.2376, 0.9902, 1.1451, 1.1764, 1.124, 1.1977, 1.2753, 1.3048, 1.1783, 1.0983, 1.103, 1.2604, 1.2215, 1.0791, 1.2442, 1.2773, 1.1732, 1.361, 1.3437, 1.1177, 1.132, 1.2052, 1.2742, 1.2036, 1.1288, 1.0997, 1.2294, 1.2381, 1.0623, 1.0404, 1.1173, 1.2604, 1.2581, 1.2182, 1.1831, 1.1718, 1.198, 1.2615, 1.2676, 1.239, 1.1885, 1.0976, 1.0808, 1.2218, 1.1798, 1.1609, 1.312, 1.3049, 1.2355, 1.2273, 1.2591, 1.2832, 1.2324, 1.215, 1.2395, 1.3132, 1.3856, 1.436, 1.4312, 1.395, 1.3546, 1.3808, 1.455, 1.545, 1.5113, 1.5644, 1.7018, 1.6238, 1.5901, 1.6946, 1.8104, 1.9492, 2.1107, 2.2112, 2.2626, 2.2727, 2.3794, 2.5303, 2.6909, 2.7736, 2.8397, 2.9675, 3.1515, 3.3725, 3.5994, 3.6874, 3.7088, 3.9387, 4.1025, 4.1773, 4.3195, 4.4649, 4.6009, 4.7584, 4.8771, 4.9391, 5.0545, 5.1682, 5.2438, 5.3191, 5.4022, 5.5079, 5.5665, 5.6007, 5.6526, 5.6609, 5.6538, 5.7085, 5.7801, 5.8455, 5.8202, 5.8305, 5.9095, 5.9682, 6.0177, 6.0578, 6.0555, 6.0501, 6.0706, 6.0924, 6.1129, 6.1293, 6.1358, 6.1268, 6.0857, 6.0674, 6.0707, 6.0472, 6.0119, 5.9671, 5.9168, 5.861, 5.7998, 5.734, 5.6616, 5.5794, 5.4961, 5.4138, 5.3379, 5.2458, 5.1496, 5.0905, 5.0596, 5.0427, 4.9651, 4.8852, 4.8254, 4.7739, 4.7265, 4.679, 4.6186, 4.5573, 4.5101, 4.4771, 4.452, 4.4131, 4.3854, 4.3682, 4.3235, 4.2964, 4.3004, 4.259, 4.2216, 4.2231, 4.175, 4.1168, 4.1189, 4.1106, 4.092, 4.0874, 4.0619, 4.0113, 4.0133, 4.0112, 3.976, 3.9535, 3.9298, 3.8935, 3.8517, 3.8059, 3.7567, 3.7257, 3.7041, 3.6035, 3.5324, 3.5303, 3.5289, 3.5266, 3.5164, 3.4951, 3.4655, 3.4262, 3.4152, 3.4323, 3.4446, 3.451, 3.4488, 3.4296, 3.4072, 3.3963, 3.3808, 3.3536, 3.2999, 3.2408, 3.178, 3.1026, 3.0341, 2.9771, 2.9042, 2.8117, 2.6901, 2.5728, 2.4732, 2.4172, 2.3742, 2.3363, 2.2857, 2.2376, 2.199, 2.1832, 2.185, 2.2041, 2.2047, 2.1834, 2.1284, 2.099, 2.098, 2.0596, 2.0155, 1.9802, 1.9303, 1.8907, 1.9156, 1.8933, 1.8374, 1.8214, 1.7915, 1.7387, 1.7585, 1.797, 1.8074, 1.8119, 1.813, 1.8108, 1.8315, 1.8744, 1.9083, 1.9385, 1.9648, 2.0145, 2.0861, 2.1785, 2.2888, 2.4167, 2.559, 2.7443, 2.9823, 3.2525, 3.5601, 3.9133, 4.2635, 4.6202, 5.0234, 5.4439, 5.8737, 6.3252, 6.7681, 7.1716, 7.5504, 7.9136, 8.2902, 8.6457, 8.9756, 9.2922, 9.5905, 9.8683, 10.1315, 10.3813, 10.619, 10.85, 11.0779, 11.3233, 11.5409, 11.7024, 11.8914, 12.0854, 12.2454, 12.4123, 12.5898, 12.7651, 12.9289, 13.0741, 13.2106, 13.3307, 13.4147, 13.5146, 13.6338, 13.7416, 13.8386, 13.9225, 13.9963, 14.0638, 14.1318, 14.1975, 14.2603, 14.3174, 14.3702, 14.419, 14.4709, 14.5164, 14.5362, 14.5608, 14.5926, 14.6151, 14.6384, 14.6675, 14.6835, 14.6917, 14.7012, 14.7033, 14.7002, 14.7204, 14.745, 14.759, 14.7403, 14.7095, 14.7382, 14.7682, 14.7827, 14.7718, 14.7562, 14.7565, 14.7581, 14.7597, 14.7571, 14.7629, 14.7802, 14.7943, 14.7992, 14.7795, 14.7688, 14.771, 14.7766, 14.7783, 14.7699, 14.783, 14.7994, 14.7835, 14.7905, 14.8212, 14.8108, 14.7906, 14.7861, 14.7929, 14.8049, 14.8, 14.8039, 14.8227, 14.8241, 14.8201, 14.8201, 14.8177, 14.8122, 14.8002, 14.7995, 14.8213, 14.8379, 14.8473, 14.8418, 14.8411, 14.849, 14.8412, 14.8363, 14.8541, 14.8615, 14.8598, 14.8554, 14.8597, 14.88, 14.8732, 14.8587, 14.8715, 14.8732, 14.8616, 14.8634, 14.8637, 14.8456, 14.8632, 14.8989, 14.8872, 14.8727, 14.871, 14.8752, 14.884, 14.8951, 14.9087, 14.9234, 14.9339, 14.9278, 14.8853, 14.8846, 14.9154, 14.9297, 14.9184, 14.8689, 14.8783, 14.9074, 14.8896, 14.8728, 14.8665, 14.8747, 14.8828, 14.8729, 14.884, 14.911, 14.8871, 14.8727, 14.9012, 14.9141, 14.9122, 14.8985, 14.8974, 14.9163, 14.9142, 14.9023, 14.8951, 14.8996, 14.9152, 14.9326, 14.9371, 14.9087, 14.8938, 14.8897, 14.8749, 14.867, 14.8754, 14.8785, 14.8716, 14.8363, 14.8144, 14.8191, 14.8671, 14.9138, 14.8701, 14.8502, 14.8772, 14.8789, 14.8642, 14.8317, 14.8244, 14.8422, 14.8442, 14.8445, 14.8502, 14.8513, 14.847, 14.8321, 14.823, 14.8295, 14.8422, 14.8607, 14.8909, 14.8959, 14.8658, 14.8734, 14.8861, 14.8448, 14.8239, 14.8372, 14.8093, 14.7753, 14.7741, 14.7824, 14.7962, 14.8128, 14.8133, 14.7726, 14.7462, 14.7417, 14.7677, 14.7902, 14.7801, 14.7701, 14.759, 14.7332, 14.7062, 14.6847, 14.6782, 14.6802, 14.6578, 14.6475, 14.6707, 14.6644, 14.6433, 14.664, 14.6759, 14.6586, 14.6206, 14.5773, 14.5647, 14.5576, 14.5489, 14.5231, 14.4888, 14.4613, 14.4457, 14.4443, 14.4541, 14.4682, 14.4716, 14.4707, 14.4662, 14.4179, 14.3591, 14.3537, 14.3291, 14.2706, 14.2287, 14.2087, 14.2371, 14.2232, 14.1461, 14.0927, 14.0571, 14.0395, 14.0126, 13.9703, 13.9776, 13.9977, 13.9602, 13.9558, 14.0033, 14.0368, 14.0433, 13.9804, 13.9623, 14.0143, 13.9793, 13.9107, 13.9163, 13.9231, 13.9134, 13.919, 13.9396, 13.9922, 13.998, 13.9349, 13.9301, 13.96, 14.0045, 13.9968, 13.8951, 13.8752, 13.897, 13.8711, 13.9007, 14.0414, 14.0253, 13.9068, 13.9302, 13.9855, 14.0284, 14.0604, 14.0743, 14.0317, 13.9869, 13.9817, 13.9765, 13.975, 14.0585, 14.1354, 14.1155, 14.0591, 13.9863, 14.0326, 14.1237, 14.1935, 14.213, 14.1711, 14.1359, 14.1105, 14.1159, 14.1214, 14.1186, 14.1605, 14.1881, 14.0298, 13.9426, 14.0448, 14.14, 14.218, 14.2512, 14.2572, 14.2488, 14.179, 14.0659, 14.1359, 14.2265, 14.116, 14.1073, 14.2622, 14.2503, 14.1804, 14.2735, 14.3816, 14.4607, 14.4071, 14.2692, 14.2642, 14.26, 14.1628, 14.1423, 14.1934, 14.0866, 13.9905, 14.1269, 14.2559, 14.3261, 14.3415, 14.3122, 14.2267, 14.2317, 14.4182, 14.4044, 14.2525, 14.2735, 14.2358, 13.9413, 13.8361, 13.9684, 14.4353, 14.8507, 14.4127, 14.0409, 14.113, 14.3471, 14.6841, 14.927, 15.0718, 15.1031, 14.8314, 14.3134, 14.2584, 14.3669, 14.2596, 14.2085, 14.3073, 14.4755, 14.6991, 14.9879, 15.1105, 14.8203, 14.6206, 14.6005, 14.5365, 14.3672, 13.7926, 13.5136, 13.8953, 13.9656, 13.7841, 14.8229, 15.7109, 14.4502, 13.8112, 14.4028, 14.2681]

**Primer acercamiento🙀**

In [5]:
import polars as pl
from functools import partial

# Función para extraer valores inicial y final de Time de manera robusta
def extract_time(line):
    if "Time:" in line:  # Verificar si la línea contiene 'Time:'
        print(f"Línea encontrada: {line}")  # Depuración para ver la línea encontrada
        # Encontrar la parte después de 'Time:'
        try:
            time_str = line.split("Time:")[1].strip()  # Parte después de 'Time:'
            values = time_str.split(',')  # Dividir por coma
            print(f"Valores extraídos: {values}")  # Depuración para ver los valores extraídos
            if len(values) == 2:
                return values[0].strip(), values[1].strip()  # Retornar los tiempos inicial y final
            elif len(values) == 1:
                return values[0].strip(), None  # Si solo hay un valor
        except Exception as e:
            print(f"Error en la extracción de Time: {e}")
    return None, None

# Función para extraer valores inicial y final de una línea
def extract_values(line, keyword):
    if keyword in line:
        values = line.split(":")[1].strip().split(',')
        return values if len(values) == 2 else [values[0], None]  # Si no hay dos valores, manejar el caso
    return [None, None]

# Función genérica para aplicar extracción según las palabras clave
def extract_by_keyword(keyword, lines):
    extractor = partial(extract_values, keyword=keyword)
    return next(filter(lambda result: result != [None, None], map(extractor, lines)), [None, None])

# Función principal para procesar el archivo y retornar un DataFrame
def process_file(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()

    # Inicializar variables para Time
    initial_time, end_time = None, None

    # Extraer los tiempos
    for line in lines:
        line = line.strip()  # Eliminar espacios en blanco al inicio y final de cada línea
        initial_time, end_time = extract_time(line)
        if initial_time and end_time:
            break  # Romper el bucle si encontramos ambos tiempos

    # Definir las claves y palabras clave para extraer los valores
    extraction_map = {
        "InitialDate": "Date",
        "EndDate": "Date",
        "InitialTime": initial_time,
        "EndTime": end_time,
        "InitialTemp": "Temperature (C)",
        "EndTemp": "Temperature (C)",
        "InitialVoltage": "Battery Voltage",
        "EndVoltage": "Battery Voltage"
    }

    # Aplicar extracción a cada campo y construir el diccionario
    data = {}
    for key, keyword in extraction_map.items():
        if "Time" in key:  # Usar los tiempos extraídos
            data[key] = keyword
        else:
            initial, final = extract_by_keyword(keyword, lines)
            if "Initial" in key:
                data[key] = initial
            elif "End" in key:
                data[key] = final

    return pl.DataFrame([data])

# Ejecutar el procesamiento y mostrar el DataFrame
url = file_path  # Asegúrate de poner la ruta correcta aquí
df = process_file(url)
df

Línea encontrada: Time: 10:49:25.71,11:02:16.86
Valores extraídos: ['10:49:25.71', '11:02:16.86']

shape: (1, 8)
┌────────────┬────────────┬────────────┬────────────┬────────────┬─────────┬───────────┬───────────┐
│ InitialDat ┆ EndDate    ┆ InitialTim ┆ EndTime    ┆ InitialTem ┆ EndTemp ┆ InitialVo ┆ EndVoltag │
│ e          ┆ ---        ┆ e          ┆ ---        ┆ p          ┆ ---     ┆ ltage     ┆ e         │
│ ---        ┆ str        ┆ ---        ┆ str        ┆ ---        ┆ str     ┆ ---       ┆ ---       │
│ str        ┆            ┆ str        ┆            ┆ str        ┆         ┆ str       ┆ str       │
╞════════════╪════════════╪════════════╪════════════╪════════════╪═════════╪═══════════╪═══════════╡
│ 06/21/2023 ┆ 06/21/2023 ┆ 10:49:25.7 ┆ 11:02:16.8 ┆ 29.04      ┆ 31.29   ┆ 8.27      ┆ 8.20      │
│            ┆            ┆ 1          ┆ 6          ┆            ┆         ┆           ┆           │
└────────────┴────────────┴────────────┴────────────┴────────────┴─────────┴───────────┴───────────┘

In [11]:
import polars as pl

# Función para extraer valores inicial y final de Averages
def extract_averages(line):
    if "Averages" in line:
        values = line.split(":")[1].strip().split(',')
        return values if len(values) == 2 else [values[0], None]  # Si no hay dos valores, manejar el caso
    return [None, None]

# Función principal para procesar el archivo y retornar un DataFrame solo con Averages
def process_averages(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()

    # Inicializar variables para Averages
    averages_initial, averages_final = None, None

    # Iterar sobre las líneas para encontrar la línea que contiene Averages
    for line in lines:
        line = line.strip()  # Eliminar espacios en blanco al inicio y final de cada línea
        averages_initial, averages_final = extract_averages(line)
        if averages_initial and averages_final:
            break  # Romper el bucle si encontramos ambos valores

    # Crear un DataFrame solo con los promedios extraídos
    data = {"AveragesInitial": averages_initial, "AveragesFinal": averages_final}

    # Imprimir los valores extraídos para verificación
    print(f"AveragesInitial: {averages_initial}, AveragesFinal: {averages_final}")

    return pl.DataFrame([data])

# Ejecutar el procesamiento y mostrar el DataFrame solo con Averages
url = file_path
df_averages = process_averages(url)
df_averages

AveragesInitial: 10, AveragesFinal: 10

shape: (1, 2)
┌─────────────────┬───────────────┐
│ AveragesInitial ┆ AveragesFinal │
│ ---             ┆ ---           │
│ str             ┆ str           │
╞═════════════════╪═══════════════╡
│ 10              ┆ 10            │
└─────────────────┴───────────────┘

In [34]:
import polars as pl
from functools import partial

# Función para extraer valores inicial y final de Averages
def extract_averages(line):
    if "Averages" in line:
        values = line.split(":")[1].strip().split(',')
        return values if len(values) == 2 else [values[0], None]  # Si no hay dos valores, manejar el caso
    return [None, None]

# Función para extraer valores inicial y final de Time de manera robusta
def extract_time(line):
    if "Time:" in line:  # Verificar si la línea contiene 'Time:'
        try:
            time_str = line.split("Time:")[1].strip()  # Parte después de 'Time:'
            values = time_str.split(',')  # Dividir por coma
            if len(values) == 2:
                return values[0].strip(), values[1].strip()  # Retornar los tiempos inicial y final
            elif len(values) == 1:
                return values[0].strip(), None  # Si solo hay un valor
        except Exception as e:
            print(f"Error en la extracción de Time: {e}")
    return None, None

# Función para extraer valores inicial y final de una línea según una palabra clave
def extract_values(line, keyword):
    if keyword in line:
        values = line.split(":")[1].strip().split(',')
        return values if len(values) == 2 else [values[0], None]  # Si no hay dos valores, manejar el caso
    return [None, None]

# Función genérica para aplicar extracción según las palabras clave
def extract_by_keyword(keyword, lines):
    extractor = partial(extract_values, keyword=keyword)
    return next(filter(lambda result: result != [None, None], map(extractor, lines)), [None, None])

# Función principal para procesar el archivo y retornar un DataFrame unificado
def process_file(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()

    # Inicializar variables para Time y Averages
    initial_time, end_time = None, None
    averages_initial, averages_final = None, None

    # Extraer Time y Averages
    for line in lines:
        line = line.strip()  # Eliminar espacios en blanco al inicio y final de cada línea
        
        # Extraer Time
        if not initial_time or not end_time:
            initial_time, end_time = extract_time(line)

        # Extraer Averages
        if not averages_initial or not averages_final:
            averages_initial, averages_final = extract_averages(line)

        if initial_time and end_time and averages_initial and averages_final:
            break  # Romper el bucle si ya hemos encontrado todo lo necesario

    # Definir las claves y palabras clave para extraer los valores adicionales
    extraction_map = {
        "InitialDate": "Date",
        "EndDate": "Date",
        "InitialTemp": "Temperature (C)",
        "EndTemp": "Temperature (C)",
        "InitialVoltage": "Battery Voltage",
        "EndVoltage": "Battery Voltage"
    }

    # Aplicar extracción a cada campo y construir el diccionario de datos
    data = {
        "InitialTime": initial_time,
        "EndTime": end_time,
        "AveragesInitial": averages_initial,
        "AveragesFinal": averages_final
    }

    for key, keyword in extraction_map.items():
        initial, final = extract_by_keyword(keyword, lines)
        if "Initial" in key:
            data[key] = initial
        elif "End" in key:
            data[key] = final

    # Crear un DataFrame final con todos los datos
    return pl.DataFrame([data])

# Ejecutar el procesamiento y mostrar el DataFrame
url = file_path
df = process_file(url)
df

shape: (1, 10)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ InitialTim ┆ EndTime   ┆ AveragesI ┆ AveragesF ┆ … ┆ InitialTe ┆ EndTemp ┆ InitialVo ┆ EndVoltag │
│ e          ┆ ---       ┆ nitial    ┆ inal      ┆   ┆ mp        ┆ ---     ┆ ltage     ┆ e         │
│ ---        ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str     ┆ ---       ┆ ---       │
│ str        ┆           ┆ str       ┆ str       ┆   ┆ str       ┆         ┆ str       ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ 10:49:25.7 ┆ 11:02:16. ┆ 10        ┆ 10        ┆ … ┆ 29.04     ┆ 31.29   ┆ 8.27      ┆ 8.20      │
│ 1          ┆ 86        ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

In [37]:
import polars as pl
from functools import partial

# Función para extraer valores de líneas con formato clave: valor, con coma
def extract_values(line, keyword):
    if keyword in line:
        try:
            values = line.split(":")[1].strip().split(',')
            return [v.strip().replace('"', '') for v in values] if len(values) == 2 else [values[0].strip().replace('"', ''), None]
        except (IndexError, ValueError) as e:
            print(f"Error al extraer valores para '{keyword}': {e}")
            return [None, None]
    return [None, None]

# Función para extraer Time de manera robusta
def extract_time(line):
    if "Time:" in line:  # Verificar si la línea contiene 'Time:'
        try:
            time_str = line.split("Time:")[1].strip()  # Parte después de 'Time:'
            values = time_str.split(',')  # Dividir por coma
            if len(values) == 2:
                return values[0].strip().replace('"', ''), values[1].strip().replace('"', '')  # Retornar tiempos inicial y final sin comillas
            elif len(values) == 1:
                return values[0].strip().replace('"', ''), None  # Si solo hay un valor
        except Exception as e:
            print(f"Error en la extracción de Time: {e}")
    return None, None

# Función para extraer Averages
def extract_averages(line):
    return extract_values(line, "Averages")

# Función genérica para aplicar extracción según las palabras clave
def extract_by_keyword(keyword, lines):
    extractor = partial(extract_values, keyword=keyword)
    return next(filter(lambda result: result != [None, None], map(extractor, lines)), [None, None])

# Función principal para procesar el archivo y retornar un DataFrame unificado
def process_file(file_path):
    with open(file_path, 'r') as file:
        lines = [line.strip() for line in file.readlines()]

    # Extraer Time y Averages
    initial_time, end_time = None, None
    averages_initial, averages_final = None, None

    for line in lines:
        if not (initial_time and end_time):
            initial_time, end_time = extract_time(line)

        if not (averages_initial and averages_final):
            averages_initial, averages_final = extract_averages(line)

        if initial_time and end_time and averages_initial and averages_final:
            break  # Romper si ya hemos extraído los valores necesarios

    # Definir las palabras clave para extraer valores adicionales
    extraction_map = {
        "InitialDate": "Date",
        "EndDate": "Date",
        "InitialTemp": "Temperature (C)",
        "EndTemp": "Temperature (C)",
        "InitialVoltage": "Battery Voltage",
        "EndVoltage": "Battery Voltage"
    }

    # Aplicar la extracción para las demás palabras clave
    data = {
        "InitialTime": initial_time,
        "EndTime": end_time,
        "AveragesInitial": averages_initial,
        "AveragesFinal": averages_final
    }

    for key, keyword in extraction_map.items():
        initial, final = extract_by_keyword(keyword, lines)
        if "Initial" in key:
            data[key] = initial
        elif "End" in key:
            data[key] = final

    # Crear el DataFrame final
    return pl.DataFrame([data])

# Ejemplo de uso
file_path = file_path
df = process_file(file_path)
df

shape: (1, 10)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ InitialTim ┆ EndTime   ┆ AveragesI ┆ AveragesF ┆ … ┆ InitialTe ┆ EndTemp ┆ InitialVo ┆ EndVoltag │
│ e          ┆ ---       ┆ nitial    ┆ inal      ┆   ┆ mp        ┆ ---     ┆ ltage     ┆ e         │
│ ---        ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str     ┆ ---       ┆ ---       │
│ str        ┆           ┆ str       ┆ str       ┆   ┆ str       ┆         ┆ str       ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ 10:49:25.7 ┆ 11:02:16. ┆ 10        ┆ 10        ┆ … ┆ 29.04     ┆ 31.29   ┆ 8.27      ┆ 8.20      │
│ 1          ┆ 86        ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

In [12]:
import polars as pl
from functools import partial

# Función para extraer valores de líneas con formato clave: valor, con coma
def extract_values(line, keyword):
    if keyword in line:
        try:
            values = line.split(":")[1].strip().split(',')
            return [v.strip().replace('"', '') for v in values] if len(values) == 2 else [values[0].strip().replace('"', ''), None]
        except (IndexError, ValueError) as e:
            print(f"Error al extraer valores para '{keyword}': {e}")
            return [None, None]
    return [None, None]

# Función para extraer Time de manera robusta
def extract_time(line):
    if "Time:" in line:
        try:
            time_str = line.split("Time:")[1].strip()
            values = time_str.split(',')
            if len(values) == 2:
                return values[0].strip().replace('"', ''), values[1].strip().replace('"', '')
            elif len(values) == 1:
                return values[0].strip().replace('"', ''), None
        except Exception as e:
            print(f"Error en la extracción de Time: {e}")
    return None, None

# Función para extraer Averages
def extract_averages(line):
    return extract_values(line, "Averages")

# Función genérica para aplicar extracción según las palabras clave
def extract_by_keyword(keyword, lines):
    extractor = partial(extract_values, keyword=keyword)
    return next(filter(lambda result: result != [None, None], map(extractor, lines)), [None, None])

# Función principal para procesar el archivo y retornar un DataFrame unificado
def process_file(file_path):
    with open(file_path, 'r') as file:
        lines = [line.strip() for line in file.readlines()]

    # Extraer Time y Averages
    initial_time, end_time = None, None
    averages_initial, averages_final = None, None

    for line in lines:
        if not (initial_time and end_time):
            initial_time, end_time = extract_time(line)

        if not (averages_initial and averages_final):
            averages_initial, averages_final = extract_averages(line)

        if initial_time and end_time and averages_initial and averages_final:
            break  # Romper si ya hemos extraído los valores necesarios

    # Definir las palabras clave para extraer valores adicionales
    extraction_map = {
        "InitialDate": "Date",
        "EndDate": "Date",
        "InitialTemp": "Temperature (C)",
        "EndTemp": "Temperature (C)",
        "InitialVoltage": "Battery Voltage",
        "EndVoltage": "Battery Voltage"
    }

    # Aplicar la extracción para las demás palabras clave
    dates = {}
    temps = {}
    voltages = {}

    for key, keyword in extraction_map.items():
        initial, final = extract_by_keyword(keyword, lines)
        if "Date" in key:
            dates[key] = initial if "Initial" in key else final
        elif "Temp" in key:
            temps[key] = initial if "Initial" in key else final
        elif "Voltage" in key:
            voltages[key] = initial if "Initial" in key else final

    # Crear un diccionario con el nuevo orden: Date, Time, Temperature, Battery Voltage, Averages
    data = {
        "InitialDate": dates.get("InitialDate"),
        "EndDate": dates.get("EndDate"),
        "InitialTime": initial_time,
        "EndTime": end_time,
        "InitialTemperature": temps.get("InitialTemp"),
        "EndTemperature": temps.get("EndTemp"),
        "InitialVoltage": voltages.get("InitialVoltage"),
        "EndVoltage": voltages.get("EndVoltage"),
        "InitialAverages": averages_initial,
        "EndAverages": averages_final
    }

    # Crear el DataFrame final con las columnas ordenadas
    columns_order = [
        "InitialDate",
        "EndDate",
        "InitialTime",
        "EndTime", 
        "InitialTemperature",
        "EndTemperature",
        "InitialVoltage",
        "EndVoltage",
                     "InitialAverages", "EndAverages"]

    return pl.DataFrame([data])[columns_order]

# Ejemplo de uso
url = file_path
df = process_file(url)
df

shape: (1, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ InitialDa ┆ EndDate   ┆ InitialTi ┆ EndTime   ┆ … ┆ InitialVo ┆ EndVoltag ┆ InitialAv ┆ EndAvera │
│ te        ┆ ---       ┆ me        ┆ ---       ┆   ┆ ltage     ┆ e         ┆ erages    ┆ ges      │
│ ---       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆           ┆ str       ┆           ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 06/21/202 ┆ 06/21/202 ┆ 10:49:25. ┆ 11:02:16. ┆ … ┆ 8.27      ┆ 8.20      ┆ 10        ┆ 10       │
│ 3         ┆ 3         ┆ 71        ┆ 86        ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [23]:
# utils.py
import polars as pl
from functools import partial

def extract_values(line, keyword):
    if keyword in line:
        try:
            values = line.split(":")[1].strip().split(',')
            return [v.strip().replace('"', '') for v in values] if len(values) == 2 else [values[0].strip().replace('"', ''), None]
        except (IndexError, ValueError):
            return [None, None]
    return [None, None]

def extract_time(line):
    if "Time:" in line:
        try:
            values = line.split("Time:")[1].strip().split(',')
            return values[0].strip().replace('"', ''), (values[1].strip().replace('"', '') if len(values) > 1 else None)
        except Exception:
            return None, None
    return None, None

def extract_averages(line):
    return extract_values(line, "Averages")

def extract_by_keyword(keyword, lines):
    extractor = partial(extract_values, keyword=keyword)
    return next(filter(lambda result: result != [None, None], map(extractor, lines)), [None, None])

def process_file(file_path):
    with open(file_path, 'r') as file:
        lines = [line.strip() for line in file.readlines()]

    initial_time, end_time = None, None
    averages_initial, averages_final = None, None

    for line in lines:
        if not (initial_time and end_time):
            initial_time, end_time = extract_time(line)
        if not (averages_initial and averages_final):
            averages_initial, averages_final = extract_averages(line)
        if initial_time and end_time and averages_initial and averages_final:
            break

    extraction_map = {
        "InitialDate": "Date",
        "EndDate": "Date",
        "InitialTemp": "Temperature (C)",
        "EndTemp": "Temperature (C)",
        "InitialVoltage": "Battery Voltage",
        "EndVoltage": "Battery Voltage"
    }

    dates, temps, voltages = {}, {}, {}
    for key, keyword in extraction_map.items():
        initial, final = extract_by_keyword(keyword, lines)
        if "Date" in key:
            dates[key] = initial if "Initial" in key else final
        elif "Temp" in key:
            temps[key] = initial if "Initial" in key else final
        elif "Voltage" in key:
            voltages[key] = initial if "Initial" in key else final

    data = {
        "InitialDate": dates.get("InitialDate"),
        "EndDate": dates.get("EndDate"),
        "InitialTime": initial_time,
        "EndTime": end_time,
        "InitialTemperature": temps.get("InitialTemp"),
        "EndTemperature": temps.get("EndTemp"),
        "InitialVoltage": voltages.get("InitialVoltage"),
        "EndVoltage": voltages.get("EndVoltage"),
        "InitialAverages": averages_initial,
        "EndAverages": averages_final
    }

    columns_order = [
        "InitialDate", "EndDate", "InitialTime", "EndTime", 
        "InitialTemperature", "EndTemperature", 
        "InitialVoltage", "EndVoltage", 
        "InitialAverages", "EndAverages"
    ]
    return pl.DataFrame([data])[columns_order]

url = file_path
df = process_file(url)
df

shape: (1, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ InitialDa ┆ EndDate   ┆ InitialTi ┆ EndTime   ┆ … ┆ InitialVo ┆ EndVoltag ┆ InitialAv ┆ EndAvera │
│ te        ┆ ---       ┆ me        ┆ ---       ┆   ┆ ltage     ┆ e         ┆ erages    ┆ ges      │
│ ---       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆           ┆ str       ┆           ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 06/21/202 ┆ 06/21/202 ┆ 10:49:25. ┆ 11:02:16. ┆ … ┆ 8.27      ┆ 8.20      ┆ 10        ┆ 10       │
│ 3         ┆ 3         ┆ 71        ┆ 86        ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘