In [3]:
import pandas as pd

In [2]:
anime_df = pd.read_csv("../anime.csv")
print(anime_df.head())

   anime_id                              name  \
0     32281                    Kimi no Na wa.
1      5114  Fullmetal Alchemist: Brotherhood
2     28977                          Gintama°
3      9253                       Steins;Gate
4      9969                     Gintama&#039;

                                               genre   type episodes  rating  \
0               Drama, Romance, School, Supernatural  Movie        1    9.37
1  Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64    9.26
2  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.25
3                                   Sci-Fi, Thriller     TV       24    9.17
4  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.16

   members
0   200630
1   793665
2   114262
3   673572
4   151266

In [13]:
intersted = anime_df[["name", "genre", "episodes"]]

In [14]:
intersted.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      12294 non-null  object
 1   genre     12232 non-null  object
 2   episodes  12294 non-null  object
dtypes: object(3)
memory usage: 288.3+ KB

In [19]:
intersted.drop_duplicates().head(10)

,name,genre,episodes
0,Kimi no Na wa.,"Drama, Romance, School, Supernatural",1
1,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",64
2,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",51
3,Steins;Gate,"Sci-Fi, Thriller",24
4,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",51
5,Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...,"Comedy, Drama, School, Shounen, Sports",10
6,Hunter x Hunter (2011),"Action, Adventure, Shounen, Super Power",148
7,Ginga Eiyuu Densetsu,"Drama, Military, Sci-Fi, Space",110
8,Gintama Movie: Kanketsu-hen - Yorozuya yo Eien...,"Action, Comedy, Historical, Parody, Samurai, S...",1
9,Gintama&#039;: Enchousen,"Action, Comedy, Historical, Parody, Samurai, S...",13

In [17]:
intersted.head()

,name,genre,episodes
0,Kimi no Na wa.,"Drama, Romance, School, Supernatural",1
1,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",64
2,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",51
3,Steins;Gate,"Sci-Fi, Thriller",24
4,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",51

In [25]:
print(intersted['name'].count(),intersted['genre'].count(),intersted['episodes'].count())

12294 12232 12294